- import_tasks: ../../common/tasks/ensure-apt-not-locked.yml

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: yes

- name: Check for Kubernetes GPG key
  stat:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  register: gpgkey

- name: Download Kubernetes GPG key (compatible pkgs.k8s.io, officiel)
  get_url:
    url: https://pkgs.k8s.io/core/stable/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    mode: "0644"
  when: not gpgkey.stat.exists
  become: yes

- name: Convert Kubernetes GPG key
  command: >
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  become: yes

- name: Add Kubernetes repository (repo stable officiel)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core/stable/deb/ /"
    state: present
    filename: kubernetes
  become: yes

- name: Install Kubernetes packages robustly
  apt:
    name:
      - kubelet={{ kubernetes_version }}
      - kubeadm={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
    update_cache: yes
    state: present
    lock_timeout: 300
  become: yes
  register: kubepkgs
  until: kubepkgs is succeeded
  retries: 6
  delay: 10
# EOF
